-- PRODUCTO
INSERT INTO producto

SELECT DISTINCT PRODUCT, COFFEA, VARIETAL, ORIGIN, ROASTING, DECAF
FROM fsdb.catalogue

WHERE PRODUCT is NOT NULL and COFFEA is NOT NULL and VARIETAL is NOT NULL
and ORIGIN is NOT NULL and ROASTING is NOT NULL and DECAF is NOT NULL; 

-- FORMATO_COMERCIALIZACION
INSERT INTO formato_comercializacion

SELECT DISTINCT PRODUCT, COFFEA, VARIETAL, ORIGIN, ROASTING, DECAF, fsdb.catalogue.FORMAT,
PACKAGING
FROM fsdb.catalogue

WHERE PRODUCT is NOT NULL and COFFEA is NOT NULL and VARIETAL is NOT NULL
and ORIGIN is NOT NULL and ROASTING is NOT NULL and DECAF is NOT NULL 
and fsdb.catalogue.FORMAT is NOT NULL and PACKAGING is NOT NULL;

-- REFERENCIA
INSERT INTO referencia

SELECT DISTINCT BARCODE, PRODUCT, COFFEA, VARIETAL, ORIGIN, ROASTING, DECAF, RETAIL_PRICE,
TO_NUMBER(CUR_STOCK), TO_NUMBER(MIN_STOCK),TO_NUMBER(MAX_STOCK)
FROM fsdb.catalogue

WHERE BARCODE is NOT NULL and PRODUCT is NOT NULL and COFFEA is NOT NULL and VARIETAL is NOT NULL and
ORIGIN is NOT NULL and ROASTING is NOT NULL and DECAF is NOT NULL and RETAIL_PRICE is NOT NULL and
CUR_STOCK is NOT NULL and MIN_STOCK is NOT NULL and MAX_STOCK is NOT NULL;

-- PROVEEDOR
INSERT INTO proveedor

SELECT DISTINCT PROV_TAXID, SUPPLIER, PROV_PERSON, PROV_EMAIL, TO_NUMBER(PROV_MOBILE), PROV_BANKACC,
PROV_ADDRESS, PROV_COUNTRY
FROM fsdb.catalogue

WHERE PROV_TAXID is NOT NULL and SUPPLIER is NOT NULL and PROV_PERSON is NOT NULL 
and PROV_EMAIL is NOT NULL and PROV_MOBILE is NOT NULL and PROV_BANKACC is NOT NULL
and PROV_ADDRESS is NOT NULL and PROV_COUNTRY is NOT NULL;

-- REPONER
INSERT INTO reponer

SELECT DISTINCT BARCODE, ORDERDATE, PROV_TAXID, ORDERTIME, MAX(COST_PRICE)
FROM fsdb.catalogue 

NATURAL JOIN fsdb.trolley WHERE PROV_TAXID is NOT NULL and COST_PRICE is NOT NULL
and BARCODE is NOT NULL and ORDERDATE is NOT NULL and ORDERTIME is NOT NULL
GROUP BY BARCODE, ORDERDATE, PROV_TAXID, ORDERTIME;

-- CLIENTE_REGISTRADO
INSERT INTO cliente_registrado(nombre_usuario, contraseña, fecha_registro, hora_registro, nombre_cliente, 
apellido1_cliente, apellido2_cliente, telefono, correo_usuario)

SELECT DISTINCT USERNAME, USER_PASSW, REG_DATE, REG_TIME, CLIENT_NAME, CLIENT_SURN1, CLIENT_SURN2,
TO_NUMBER(CLIENT_MOBILE), CLIENT_EMAIL
FROM fsdb.trolley

WHERE USERNAME is NOT NULL and USER_PASSW is NOT NULL and REG_DATE is NOT NULL and REG_TIME is NOT NULL
and CLIENT_NAME is NOT NULL and CLIENT_SURN1 is NOT NULL;

-- PAGOS
INSERT INTO pagos

SELECT DISTINCT TO_NUMBER(CARD_NUMBER), USERNAME, CARD_HOLDER, CARD_COMPANY,
CARD_EXPIRATN, PAYMENT_TYPE, PAYMENT_DATE, PAYMENT_TIME
FROM fsdb.trolley

WHERE CARD_NUMBER is NOT NULL and USERNAME is NOT NULL and CARD_HOLDER is NOT NULL
and CARD_COMPANY is NOT NULL and CARD_EXPIRATN is NOT NULL and PAYMENT_TYPE is NOT NULL
and PAYMENT_DATE is NOT NULL and PAYMENT_TIME is NOT NULL;

-- DIRECCIONES_ENTREGA
INSERT INTO direccion_entrega

SELECT DISTINCT DLIV_WAYTYPE, DLIV_WAYNAME, USERNAME, DLIV_GATE, TO_NUMBER(DLIV_BLOCK), DLIV_STAIRW, DLIV_FLOOR,
DLIV_DOOR, TO_NUMBER(DLIV_ZIP), DLIV_TOWN, DLIV_COUNTRY
FROM fsdb.trolley

WHERE DLIV_WAYTYPE is NOT NULL and DLIV_WAYNAME is NOT NULL and DLIV_GATE is NOT NULL and DLIV_TOWN is NOT NULL and 
DLIV_COUNTRY is NOT NULL;

-- DIRECCIONES_FACTURACION
INSERT INTO direccion_facturacion

SELECT DISTINCT BILL_WAYTYPE, BILL_WAYNAME, USERNAME, BILL_GATE, TO_NUMBER(BILL_BLOCK), BILL_STAIRW, BILL_FLOOR,
BILL_DOOR, TO_NUMBER(BILL_ZIP), BILL_TOWN, BILL_COUNTRY
FROM fsdb.trolley

WHERE BILL_WAYTYPE is NOT NULL and BILL_WAYNAME is NOT NULL and BILL_GATE is NOT NULL and BILL_TOWN is NOT NULL and 
BILL_COUNTRY is NOT NULL;

-- COMPRAS
INSERT INTO compras(cliente_nombre_usuario, hora_compra, referencia_codigo_barras, fecha_compra, 
direccion_entrega_tipo_via, direccion_entrega_nombre_via, direccion_entrega_num_inmueble,
direccion_entrega_ciudad, direccion_entrega_pais, nombre_comprador, apellido_comprador,
direccion_facturacion_tipo_via, direccion_facturacion_nombre_via, 
direccion_facturacion_num_inmueble, direccion_facturacion_ciudad, direccion_facturacion_pais,
correo_comprador, telefono_comprador, pagos_num_tarjeta, pagos_fecha_pago, pagos_hora_pago, cantidad,
fecha_entrega, hora_entrega)

SELECT USERNAME, ORDERTIME, BARCODE, ORDERDATE, DLIV_WAYTYPE, DLIV_WAYNAME, 
DLIV_GATE, DLIV_TOWN, DLIV_COUNTRY, CLIENT_NAME, CLIENT_SURN1, BILL_WAYTYPE, BILL_WAYNAME,
BILL_GATE, BILL_TOWN, BILL_COUNTRY, CLIENT_EMAIL, TO_NUMBER(CLIENT_MOBILE), TO_NUMBER(CARD_NUMBER), 
PAYMENT_DATE, PAYMENT_TIME, TO_NUMBER(QUANTITY), DLIV_DATE, DLIV_TIME
FROM fsdb.trolley 

WHERE USERNAME is NOT NULL and ORDERDATE is NOT NULL and ORDERTIME is NOT NULL and BARCODE is NOT NULL
and DLIV_WAYTYPE is NOT NULL and DLIV_WAYNAME is NOT NULL and DLIV_GATE is NOT NULL
and DLIV_TOWN is NOT NULL and DLIV_COUNTRY is NOT NULL and CLIENT_NAME is NOT NULL
and CLIENT_SURN1 is NOT NULL and BILL_WAYTYPE is NOT NULL and BILL_WAYNAME is NOT NULL
and BILL_GATE is NOT NULL and BILL_TOWN is NOT NULL and BILL_COUNTRY is NOT NULL
and CARD_NUMBER is NOT NULL and PAYMENT_DATE is NOT NULL and PAYMENT_TIME is NOT NULL and QUANTITY is NOT NULL
and DLIV_DATE is NOT NULL and DLIV_TIME is NOT NULL;

-- PUBLICACIONES
INSERT INTO publicaciones

SELECT DISTINCT USERNAME, TO_NUMBER(SCORE), PRODUCT, BARCODE, TITLE, TEXT, TO_NUMBER(LIKES), 
POST_DATE, POST_TIME, ENDORSED
FROM fsdb.posts

WHERE USERNAME is NOT NULL and SCORE is NOT NULL and BARCODE is NOT NULL
and TITLE is NOT NULL and TEXT is NOT NULL and LIKES is NOT NULL
and POST_DATE is NOT NULL and POST_TIME is NOT NULL and PRODUCT is NOT NULL;

-- DESCUENTOS
INSERT INTO descuentos

SELECT DISTINCT DISCOUNT, USERNAME
FROM fsdb.trolley

WHERE USERNAME is NOT NULL and DISCOUNT is NOT NULL;